### ISSUE TITLE
[fix] HomeView 리스트 수정

### ISSUE THREAD

**Issue by DecideJung1221** [DeveloperAcademy-POSTECH/2024-MC2-M10-Sandwich#115]
## Description
HomeView 리스트 수정

## To-do
- [ ] HomeView 리스트 정렬 수정
- [ ] HomeView 아이콘 수정
- [ ] HomeView live일때 삭제 금지
