### ISSUE TITLE
[feat] FinishPopupView UI 구현 

### ISSUE THREAD

**Issue by ubeeni** [DeveloperAcademy-POSTECH/2024-MC2-M10-Sandwich#14]
## Description
- FinishPopupView UI 구현
- 화면 연결

## To-do
- [x] 술자리 종료 선택 UI 구현
- [x] (술자리 종료 버튼 클릭시) 팝업 띄우기
- [ ] 더 마시기, 끝내기 버튼 연결
