### ISSUE TITLE
[feat] V1.1 업데이트 기능 추가 및 수정

### ISSUE THREAD

**Issue by thinkySide** [DeveloperAcademy-POSTECH/2024-MC2-M10-Sandwich#206]
## Description
V1.1 업데이트 기능 추가 및 수정

## To-do
- [x] 원샷 진행 중 홈 화면에서 라이브 리스트를 들어갈 때 카메라 화면을 띄우기
- [x] 카메라 화면에서 강제 종료되었을 때 ‘술자리 종료’버튼 아래로 위치 변경
- [x] 멤버카메라뷰 줌 ui 수정 (줌 매끄러움 비활성화)
