### ISSUE TITLE
[feat] TimeManger 개발

### ISSUE THREAD

**Issue by thinkySide** [DeveloperAcademy-POSTECH/2024-MC2-M10-Sandwich#38]
## Description
- TimeManager 개발
- SwiftUI AppLifeCycle을 이용한 시점 정의

## To-do
- [ ] 술자리 시작했을 때 시점
- [ ] 정각(지정한 알림 주기)마다
- [ ] 강제 종료 10분 전
- [ ] 강제 종료 되었을 때
