### ISSUE TITLE
[feat] PartyListView UI 구현

### ISSUE THREAD

**Issue by jongchang** [DeveloperAcademy-POSTECH/2024-MC2-M10-Sandwich#7]
## Description
PartyListView UI 구현합니다.

## To-do
- [x] 추가 에셋 추가
- [x] PartyListView UI 구현
- [x] (더미)데이터 연결
